version: '2'

services:
    nginx:
        image: nginx:alpine
        ports:
            - "8080:80"
        volumes:
            - ./code:/code
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    php:
        image: php:7-fpm-alpine
        volumes:
            - ./code:/code
        networks:
            - code-network
    appflow:
        image: php:7-cli
        volumes:
            - ../../:/usr/local/bin/appflow
        networks:
            - code-network

networks:
    code-network:
        driver: bridge
