---

# OSX: sudo ifconfig lo0 alias 10.200.10.1/24

version: '2'
services:
  jenkins:
    image: jenkins
    container_name: jenkins
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ~/.appflow/jenkins:/var/jenkins_home
    environment:
      - APPFLOW_DH_USERNAME=$USER
      - APPFLOW_DH_HOSTIP=$(if [[ $OSTYPE == darwin* ]]; then echo 10.200.10.1;fi)
